### ISSUE TITLE
Sponge crash after ~2 weeks of uptime

### ISSUE THREAD

**Issue by alexbyrnes** [coralproject/install#16]
Sponge may have a slow memory leak or an issue that happens very rarely. We don't have logs of this yet. 

Two possible solutions: 

Restart sponge periodically between imports
Find/fix memory leak

This ticket will be for figuring out the cause. May need to be picked up in a week or so.

**Comment by alexbyrnes** [comment]
This morning I restarted the backend and started a periodic log cleanup.  I'll check the server in a few days to see if sponge is using progressively more memory. Talked with @edefikh about ways of daemon-izing the services so they won't need to be background jobs or docker containers.

**Comment by kgardnr** [comment]
Closing, will open separate issue in Pivotal.
