### ISSUE TITLE
Build go releases for multiple os and push to s3

### ISSUE THREAD

**Issue by jde** [coralproject/install#20]
Create readily available files containing builds and scripts.

Example script to build for multiple architectures:
https://gist.github.com/wyattjoh/803cdbb8a7ff05028f403d7e3fdd34c2

Trigger builds "version=tip" on commits to master.
Trigger builds "version=${DRONE_TAG}" when a tag is applied in github

Only Trigger builds where tests pass.

**Comment by edefikh** [comment]
Tested creation of docker image locally on Jenkins for Pillar and then upload it to Docker Hub repo, bypassing automated build queue on docker hub.

working on implementing builds steps outlined in example script.

**Comment by edefikh** [comment]
solution works as expected per Wyatt
